export type ErrorCode =
  | "invalidRequest"
  | "rateLimited"
  | "unavailable"
  | "noSession"
  | "tableNotFound"
  | "tableExpired"
  | "tableExists"
  | "tableClosed"
  | "tableFull"
  | "joinFirst"
  | "notAtTable"
  | "removed"
  | "leftTable"
  | "otherTab"
  | "spectating"
  | "nameRequired"
  | "nameLength"
  | "avatarRequired"
  | "codeInvalid"
  | "optionRequired"
  | "livesRange"
  | "moveTimeRange"
  | "playerRequired"
  | "invalidBid"
  | "invalidCard"
  | "hostOnlyOptions"
  | "optionsLocked"
  | "hostOnlyBots"
  | "botsLobbyOnly"
  | "hostOnlyRemove"
  | "removeLobbyOnly"
  | "hostOnlyStart"
  | "needTwoPlayers"
  | "namesLobbyOnly"
  | "notYourBid"
  | "bidBlocked"
  | "notYourTurn"
  | "cardNotInHand"
  | "aceModeRequired"
  | "chatEmpty"
  | "chatTooLong"
  | "chatClosed"
  | "emotesPlayOnly"
  | "emoteCooldown"
  | "donationUnavailable"
  | "donationTarget"
  | "rematchNotOver"
  | "rematchPlayersOnly"
  | "rematchInvited"
  | "rematchFailed"
  | "cookies"
  | "connecting"
  | "reconnecting"
  | "connectionClosed"
  | "interrupted"
  | "timeout"
  | "unreachable"
  | "invalidResponse"
  | "statsFailed"
  | "profileFailed";

export class GameError extends Error {
  constructor(readonly code: ErrorCode) {
    super(code);
  }
}
